# Azure Cosmos DB Configuration
spring.cloud.azure.cosmos.endpoint=${COSMOS_URI:https://tvk-my-cosmos-account.documents.azure.com:443/}
spring.cloud.azure.cosmos.database=${COSMOS_DATABASE:petclinic}
spring.cloud.azure.cosmos.populate-query-metrics=false
